controller_manager:
  ros__parameters:
    update_rate: 1000 #  Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gazebo_joint_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
   
    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController
    
    joint_group_effort_controller:
      type: effort_controllers/JointGroupEffortController

joint_group_position_controller:
  ros__parameters:
    joints:
      - fr_mainbodyhip_joint
      - fr_hip1_joint
      - fr_14_joint
      - fl_mainbodyhip_joint
      - fl_hip1_joint
      - fl_14_joint
      - rr_mainbodyhip_joint
      - rr_hip1_joint
      - rr_14_joint
      - rl_mainbodyhip_joint
      - rl_hip1_joint
      - rl_14_joint

    command_interfaces:
      - position 
    state_interfaces:
      - position
      - velocity
      - effort
    gains:
      fr_mainbodyhip_joint: {p: 12, i: 0.01, d: 0.1}
      fr_hip1_joint:        {p: 12, i: 0.01, d: 0.1}
      fr_14_joint:          {p: 12, i: 0.01, d: 0.1}
      fl_mainbodyhip_joint: {p: 12, i: 0.01, d: 0.1}
      fl_hip1_joint:        {p: 12, i: 0.01, d: 0.1}
      fl_14_joint:          {p: 12, i: 0.01, d: 0.1}
      rr_mainbodyhip_joint: {p: 12, i: 0.01, d: 0.1}
      rr_hip1_joint:        {p: 12, i: 0.01, d: 0.1}
      rr_14_joint:          {p: 12, i: 0.01, d: 0.1}
      rl_mainbodyhip_joint: {p: 12, i: 0.01, d: 0.1}
      rl_hip1_joint:        {p: 12, i: 0.01, d: 0.1}
      rl_14_joint:          {p: 12, i: 0.01, d: 0.1}

joint_state_broadcaster:
  ros__parameters:
    joints:
      - fr_mainbodyhip_joint
      - fr_hip1_joint
      - fr_14_joint
      - fl_mainbodyhip_joint
      - fl_hip1_joint
      - fl_14_joint
      - rr_mainbodyhip_joint
      - rr_hip1_joint
      - rr_14_joint
      - rl_mainbodyhip_joint
      - rl_hip1_joint
      - rl_14_joint
      - fr_foot_sphere_joint
      - fl_foot_sphere_joint
      - rr_foot_sphere_joint
      - rl_foot_sphere_joint
    command_interfaces:
      - position 
    state_interfaces:
      - position
      - velocity
      - effort
