// Xbox Joystick button_map

axes[0] : 1joystick left, right
axes[1] : 1joystick up, down
axes[2] : Lt button (default 1, press til -1)
axes[3] : 2joystick left, right
axes[4] : 2joystick up, down
axes[5] : Rt button (default 1, press til -1)
axes[6] : crossjoy left, right
axes[7] : crossjoy up, down

buttons[0] : A
buttons[1] : B
buttons[2] : X
buttons[3] : Y
buttons[4] : Lb
buttons[5] : Rb
buttons[6] : back
buttons[7] : start
buttons[8] : middle